## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [ ]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [ ]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
dfbi = pd.read_csv("bridge-inspections-excerpts.csv")
dfbi

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111,random
0,53,27.0,'BEAR CREEK',46595400.0,123480300.0,2.0,9.0,1976.0,5.0,1.0,7,7,6,7,N,NaN,0.722578
1,48,323.0,'RIO GRANDE RIVER',28422090.0,100302439.0,4.0,14.0,1954.0,4.0,2.0,5,6,7,6,N,1.0,0.018212
2,48,201.0,'WILCREST DRIVE',NaN,NaN,NaN,17.0,2007.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.354428
3,17,197.0,'HICKORY CREEK TRIB',41304335.0,87522600.0,3.0,19.0,2015.0,1.0,19.0,N,N,N,7,8,NaN,0.637096
4,48,113.0,'COTTONWOOD CREEK TRIB',32351631.0,96401555.0,4.0,9.0,2006.0,1.0,19.0,N,N,N,6,7,NaN,0.075183
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,18,147.0,'BRANCH CROOKED CREEK',38075909.0,86533620.0,1.0,7.0,1987.0,3.0,19.0,N,N,N,6,4,NaN,0.279541
99996,39,87.0,'ICE CREEK',38303704.0,82391984.0,4.0,19.0,2003.0,6.0,5.0,8,8,7,8,N,1.0,0.278731
99997,51,31.0,'Flat Creek',37124185.0,79155147.0,1.0,9.0,1915.0,3.0,2.0,8,8,6,6,N,NaN,0.459534
99998,31,139.0,'STREAM',42210432.0,97310588.0,2.0,9.0,1935.0,7.0,2.0,5,4,7,8,N,1.0,0.957340
99999,22,45.0,'RODERE COULEE',29582492.0,91504056.0,1.0,17.0,1999.0,1.0,1.0,7,7,7,7,N,NaN,0.743531

In [ ]:
## call the first 10 rows
dfbi.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111,random
0,53,27.0,'BEAR CREEK',46595400.0,123480300.0,2.0,9.0,1976.0,5.0,1.0,7,7,6,7,N,NaN,0.722578
1,48,323.0,'RIO GRANDE RIVER',28422090.0,100302439.0,4.0,14.0,1954.0,4.0,2.0,5,6,7,6,N,1.0,0.018212
2,48,201.0,'WILCREST DRIVE',NaN,NaN,NaN,17.0,2007.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.354428
3,17,197.0,'HICKORY CREEK TRIB',41304335.0,87522600.0,3.0,19.0,2015.0,1.0,19.0,N,N,N,7,8,NaN,0.637096
4,48,113.0,'COTTONWOOD CREEK TRIB',32351631.0,96401555.0,4.0,9.0,2006.0,1.0,19.0,N,N,N,6,7,NaN,0.075183
5,39,57.0,'MASSIES CREEK',39452077.0,83472659.0,2.0,9.0,2011.0,5.0,5.0,9,9,9,9,N,1.0,0.306589
6,39,153.0,'SR 82',41184122.0,81270587.0,NaN,11.0,1968.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.107792
7,53,33.0,'ELLIOTT BAY',47360910.0,122202190.0,1.0,14.0,1964.0,3.0,15.0,7,6,7,8,N,3.0,0.815389
8,42,43.0,'SPRING CR City Park Dr',40152449.0,76495610.0,NaN,16.0,1961.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.829351
9,36,91.0,'SNOOK KILL',43110870.0,73422466.0,1.0,11.0,1962.0,3.0,19.0,N,N,N,7,6,NaN,0.155056

In [ ]:
## call the last 5 rows
dfbi.tail()

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111,random
99995,18,147.0,'BRANCH CROOKED CREEK',38075909.0,86533620.0,1.0,7.0,1987.0,3.0,19.0,N,N,N,6,4,NaN,0.279541
99996,39,87.0,'ICE CREEK',38303704.0,82391984.0,4.0,19.0,2003.0,6.0,5.0,8,8,7,8,N,1.0,0.278731
99997,51,31.0,'Flat Creek',37124185.0,79155147.0,1.0,9.0,1915.0,3.0,2.0,8,8,6,6,N,NaN,0.459534
99998,31,139.0,'STREAM',42210432.0,97310588.0,2.0,9.0,1935.0,7.0,2.0,5,4,7,8,N,1.0,0.957340
99999,22,45.0,'RODERE COULEE',29582492.0,91504056.0,1.0,17.0,1999.0,1.0,1.0,7,7,7,7,N,NaN,0.743531

In [ ]:
## call a 20 random rows
dfbi.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111,random
33328,30,17.0,'RR',46231014.0,105521203.0,1.0,2.0,1954.0,3.0,2.0,6,5,6,N,N,NaN,0.361253
62255,54,89.0,'LICK CREEK',37480464.0,80484151.0,1.0,9.0,1987.0,3.0,2.0,6,5,5,5,N,NaN,0.586674
23063,36,59.0,'135 135 03011116 RTE 13',40484230.0,73292878.0,1.0,14.0,1962.0,3.0,2.0,7,7,7,N,N,NaN,0.112185
11427,8,123.0,'New Cache La Poudre Cana',40285860.0,104473280.0,2.0,8.0,1997.0,3.0,2.0,7,6,7,7,N,NaN,0.162686
9974,48,153.0,'RUNNING WATER DRAW',33593954.0,101293426.0,1.0,7.0,1951.0,1.0,19.0,N,N,N,7,7,NaN,0.067241
25967,47,41.0,'BRANCH',35590522.0,85552130.0,2.0,8.0,1970.0,2.0,19.0,N,N,N,5,5,NaN,0.212447
9414,37,67.0,'US52 US311 & NC8',36055548.0,80140896.0,1.0,19.0,1963.0,4.0,2.0,5,4,5,N,N,NaN,0.120933
51318,42,11.0,'CACOOSING CREEK',40185552.0,76023506.0,3.0,9.0,1993.0,1.0,19.0,N,N,N,6,6,NaN,0.777918
23057,19,95.0,'OLD MANS CREEK',41360364.0,91585358.0,2.0,9.0,2003.0,5.0,4.0,7,8,8,8,N,NaN,0.618517
76651,29,159.0,'SMELSER CR',38473790.0,93152531.0,2.0,9.0,2008.0,5.0,2.0,7,8,9,8,N,NaN,0.065896
29737,28,91.0,'BRANCH OF HOLIDAY CREEK',31260108.0,89445517.0,2.0,9.0,2019.0,1.0,22.0,8,7,8,7,N,NaN,0.613412
57239,48,497.0,'TRIB OF BRUSHY CREEK',33252154.0,97415044.0,2.0,7.0,2006.0,5.0,2.0,7,8,6,5,N,NaN,0.528418
13105,39,21.0,'PROCTOR RUN',40092999.0,83302401.0,2.0,9.0,1963.0,5.0,5.0,8,8,8,8,N,1.0,0.365795
16518,18,89.0,'RAMP I-80/94 E TO I-65 S',41334403.0,87182783.0,1.0,11.0,2009.0,3.0,2.0,8,8,8,N,N,NaN,0.781750
57964,18,89.0,'GUTHRIE ST. EB',41382620.0,87255445.0,NaN,12.0,1980.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.536450
70849,29,95.0,'MO 7',38533474.0,94155281.0,NaN,14.0,2001.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.051315
89597,19,61.0,'N FORK LITTLE MAQUKET',42352995.0,91031696.0,2.0,9.0,2016.0,2.0,1.0,7,7,8,7,N,1.0,0.020049
23982,34,3.0,'TEANECK CREEK',40521841.0,74002963.0,2.0,16.0,1984.0,5.0,2.0,7,8,7,8,N,NaN,0.278336
53967,8,69.0,'Big Thompson River',40223278.0,105311600.0,4.0,17.0,1979.0,2.0,1.0,7,7,6,7,N,NaN,0.555471
18373,1,49.0,'TRIB. TO BIG WILLS CREEK',34245774.0,85462942.0,2.0,7.0,1990.0,1.0,19.0,N,N,N,5,7,NaN,0.558768

In [ ]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

dfbi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          99941 non-null   float64
 2   FEATURES_DESC_006A       100000 non-null  object
 3   LAT_016                  99901 non-null   float64
 4   LONG_017                 99898 non-null   float64
 5   OWNER_022                84357 non-null   float64
 6   FUNCTIONAL_CLASS_026     99851 non-null   float64
 7   YEAR_BUILT_027           99034 non-null   float64
 8   STRUCTURE_KIND_043A      98856 non-null   float64
 9   STRUCTURE_TYPE_043B      98852 non-null   float64
 10  DECK_COND_058            84358 non-null   object
 11  SUPERSTRUCTURE_COND_059  84358 non-null   object
 12  SUBSTRUCTURE_COND_060    84358 non-null   object
 13  CHANNEL_COND_061         84358 non-null   object
 14  CULVERT_COND_062         84358 non-null   object
 15  PIER_PROTECTION_111      13072 non-null   float64
 16  random                   100000 non-null  float64
dtypes: float64(10), int64(1), object(6)
memory usage: 13.0+ MB

In [ ]:
## call the top 7 rows
dfbi.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111,random
0,53,27.0,'BEAR CREEK',46595400.0,123480300.0,2.0,9.0,1976.0,5.0,1.0,7,7,6,7,N,NaN,0.722578
1,48,323.0,'RIO GRANDE RIVER',28422090.0,100302439.0,4.0,14.0,1954.0,4.0,2.0,5,6,7,6,N,1.0,0.018212
2,48,201.0,'WILCREST DRIVE',NaN,NaN,NaN,17.0,2007.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.354428
3,17,197.0,'HICKORY CREEK TRIB',41304335.0,87522600.0,3.0,19.0,2015.0,1.0,19.0,N,N,N,7,8,NaN,0.637096
4,48,113.0,'COTTONWOOD CREEK TRIB',32351631.0,96401555.0,4.0,9.0,2006.0,1.0,19.0,N,N,N,6,7,NaN,0.075183
5,39,57.0,'MASSIES CREEK',39452077.0,83472659.0,2.0,9.0,2011.0,5.0,5.0,9,9,9,9,N,1.0,0.306589
6,39,153.0,'SR 82',41184122.0,81270587.0,NaN,11.0,1968.0,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.107792

In [ ]:
## call a sample of 10
dfbi.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111,random
40212,53,59.0,'WEST FORK WASHOUGAL RIVE',45394700.0,122142100.0,2.0,9.0,1977.0,5.0,2.0,8,7,7,8,N,NaN,0.080637
25199,24,510.0,'WB MCCOMAS STREET',39160250.0,76362586.0,31.0,11.0,1978.0,4.0,2.0,6,6,7,N,N,1.0,0.033506
72224,37,119.0,'PROSPERITY CH. RD.',35220754.0,80470392.0,NaN,11.0,2013.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0.520332
51473,19,15.0,'PRAIRIE CREEK',42064916.0,93474522.0,1.0,6.0,1979.0,2.0,19.0,N,N,N,6,6,NaN,0.247111
23903,42,117.0,'OVER MITCHELL CREEK',41555940.0,77062991.0,1.0,6.0,1948.0,1.0,4.0,6,6,6,5,N,NaN,0.319011
60012,46,99.0,'TRIB TO FOUR MILE CK',43323787.0,96310773.0,2.0,9.0,1983.0,5.0,4.0,6,7,6,8,N,NaN,0.293388
26204,22,71.0,'ALGIERS CANAL',29553418.0,90012748.0,1.0,17.0,2012.0,1.0,19.0,N,N,N,7,7,1.0,0.046982
69318,8,87.0,'Beaver Creek',40044770.0,103350640.0,2.0,9.0,1950.0,3.0,2.0,6,5,6,6,N,NaN,0.424152
8225,1,73.0,'CSX R.R.',33244464.0,86580588.0,1.0,11.0,1979.0,3.0,2.0,6,6,6,7,N,NaN,0.544281
18175,31,41.0,'STREAM',41152376.0,99212196.0,1.0,2.0,1978.0,1.0,19.0,N,N,N,7,7,1.0,0.938460

In [ ]:
## call the bottom 6
dfbi.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111,random
99994,22,13.0,'BOGGY BRANCH',32335530.0,92583900.0,1.0,1.0,1964.0,1.0,19.0,N,N,N,5,6,NaN,0.108623
99995,18,147.0,'BRANCH CROOKED CREEK',38075909.0,86533620.0,1.0,7.0,1987.0,3.0,19.0,N,N,N,6,4,NaN,0.279541
99996,39,87.0,'ICE CREEK',38303704.0,82391984.0,4.0,19.0,2003.0,6.0,5.0,8,8,7,8,N,1.0,0.278731
99997,51,31.0,'Flat Creek',37124185.0,79155147.0,1.0,9.0,1915.0,3.0,2.0,8,8,6,6,N,NaN,0.459534
99998,31,139.0,'STREAM',42210432.0,97310588.0,2.0,9.0,1935.0,7.0,2.0,5,4,7,8,N,1.0,0.957340
99999,22,45.0,'RODERE COULEE',29582492.0,91504056.0,1.0,17.0,1999.0,1.0,1.0,7,7,7,7,N,NaN,0.743531

In [ ]:
## call the year built column using dot notation
dfbi.YEAR_BUILT_027

0        1976.0
1        1954.0
2        2007.0
3        2015.0
4        2006.0
          ...
99995    1987.0
99996    2003.0
99997    1915.0
99998    1935.0
99999    1999.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [ ]:
## call FEATURES_DESC_006A as a series using square bracket notation

dfbi['FEATURES_DESC_006A']

0                   'BEAR CREEK'
1             'RIO GRANDE RIVER'
2               'WILCREST DRIVE'
3           'HICKORY CREEK TRIB'
4        'COTTONWOOD CREEK TRIB'
                  ...
99995     'BRANCH CROOKED CREEK'
99996                'ICE CREEK'
99997               'Flat Creek'
99998                   'STREAM'
99999            'RODERE COULEE'
Name: FEATURES_DESC_006A, Length: 100000, dtype: object

In [ ]:
## what are the unique owner codes?
dfbi['OWNER_022'].unique()

array([ 2.,  4., nan,  3.,  1., 32., 64., 31., 62., 25., 11., 12., 63.,
       21., 74., 26., 68., 72., 69., 70., 66., 27., 56., 80., 61., 73.,
       67., 76., 79., 75., 60., 78., 55., 77.])

### What do these codes mean?