## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

## import the pandas library in this cell

import pandas as pd

## Q: LP wonders why we need to say "as pd"

### Ingest the following dataset into this note:

In [17]:
## import data and store in a dataframe call dfbi (short perhaps for dataframe bridge inspections)

## read bridge inspections csv
dfbi = pd.read_csv("bridge-inspections-excerpt.csv")

dfbi

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [18]:
## call the first 10 rows
dfbi.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [19]:
## call the last 5 rows

dfbi.tail(5)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [20]:
## call a 20 random rows
dfbi.sample()

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
29618,48,57,'DRAINAGE DITCH',28364602.0,96402855.0,1.0,2.0,1942.0,1,19.0,N,N,N,7,7,NaN

In [21]:
dfbi.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
79947,51,61,'Relocated Rte 55',38540816.0,77562074.0,1.0,1.0,1978.0,3,2.0,6,5,5,N,N,NaN
85544,51,650,'BRICK KILN CREEK',37062938.0,76233638.0,4.0,16.0,1981.0,5,4.0,6,6,6,7,N,NaN
79685,51,59,'CHAIN BRIDGE RD. RTE3547',38553825.0,77120086.0,1.0,12.0,1983.0,2,1.0,5,5,7,N,N,NaN
85437,51,590,'Pumpkin Creek',36333880.0,79235081.0,4.0,19.0,1965.0,1,4.0,6,6,5,7,N,NaN
29380,48,473,'THREEMILE CREEK',30074079.0,95492945.0,2.0,9.0,1995.0,5,0.0,7,8,8,6,N,NaN
55622,48,479,'INTERNATIONAL BLVD',27364738.0,99275677.0,1.0,14.0,2017.0,5,2.0,7,7,7,N,N,NaN
13438,48,389,'Country Club Dr',31234738.0,103301354.0,1.0,11.0,1966.0,5,2.0,6,6,6,N,N,NaN
78718,51,31,'Hills Creek',37073758.0,79121144.0,1.0,7.0,1970.0,1,5.0,7,7,6,6,N,NaN
74829,50,25,'SACKETTS BROOK',42590048.0,72312567.0,3.0,9.0,2001.0,1,1.0,8,8,8,8,N,NaN
22601,48,419,'FLAT FORK CREEK',31525072.0,94055468.0,1.0,6.0,2003.0,5,2.0,7,7,7,7,N,NaN
85656,51,680,'NS Railway',37240908.0,79132547.0,4.0,12.0,1989.0,3,2.0,7,6,6,N,N,NaN
48320,48,121,'TIMBER BRANCH',33141004.0,97035540.0,1.0,14.0,1999.0,1,19.0,N,N,N,7,7,NaN
9293,48,439,'BENBROOK LAKE TRIBUTARY',32362257.0,97241461.0,4.0,19.0,2007.0,1,19.0,N,N,N,7,7,NaN
35585,48,491,'WILLIS CREEK',30431756.0,97281695.0,2.0,9.0,1987.0,5,2.0,8,8,7,6,N,NaN
72820,49,35,'5TH &amp; 6TH W. STS. &a',40465660.0,111542390.0,NaN,19.0,1998.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
96279,53,33,'I-405',47443300.0,122111490.0,1.0,16.0,1969.0,6,5.0,7,7,6,N,N,NaN
8112,48,439,'SH-360',32424403.0,97034628.0,1.0,14.0,1981.0,5,2.0,7,7,7,N,N,NaN
30386,48,149,'FOSTER CREEK TRIB',29412722.0,96551339.0,1.0,1.0,1967.0,1,19.0,N,N,N,6,6,NaN
65877,48,29,'US 87 (Rigsby Ave.)',29235380.0,98232091.0,NaN,14.0,1964.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
66452,48,409,'IH 37',28031555.0,97461785.0,NaN,1.0,1970.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
## get basic overview of the data

dfbi.info()

##LP note, I don't remember what int64, str, float64 mean.

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

In [23]:
## what datatypes do the different columns hold?

##They hold int64, str, float64 which means... Let me ask Claude. 
## OK, Claude says int64 means whole numbers (no decimals), can be neg or pos , str = string meaning a A sequence of characters 
##(this can be a number but the number will mean something different (?))
##float 64 means "Numbers with decimals, like 3.14 or -0.001."

##the "64" means 64 bit which means the amount of data the number can hold --> it can go to about -9.2 or 9.2 trillion

In [24]:
## how many rows and columns are there

##There are 16 columns (0-15) and 100,000 rows

### Which column has the most missing data...just a quick estimate?

## 15  PIER_PROTECTION_111 has 4353 non-null items --> so only like 5000 entries

In [26]:
## call the top 7 rows

dfbi.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [27]:
## call a sample of 10

dfbi.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
39256,48,187,'IH 10',29363559.0,97522033.0,1.0,2.0,2013.0,5,2.0,7,7,7,N,N,NaN
62011,48,353,'Hopkins Rd.',32265865.0,100263205.0,NaN,17.0,1960.0,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN
29879,48,89,'BOGGY CREEK',29544618.0,96324050.0,2.0,9.0,2000.0,3,2.0,7,7,6,6,N,NaN
12761,48,135,'W SIDE DRAINAGE CHANNEL',31505240.0,102241614.0,4.0,17.0,1961.0,1,19.0,N,N,N,7,6,NaN
6112,48,251,'LOW BRANCH CREEK',32325184.0,97075025.0,1.0,16.0,2007.0,1,19.0,N,N,N,6,7,NaN
55326,48,323,'SECO CREEK',28443768.0,100294380.0,2.0,9.0,2010.0,1,19.0,N,N,N,6,6,NaN
36504,48,29,'IH 35',29171216.0,98385466.0,1.0,9.0,1974.0,5,2.0,7,7,7,N,N,NaN
12154,48,115,'SULPHUR SPRINGS DRAW',32432443.0,101572946.0,1.0,14.0,1938.0,1,19.0,N,N,N,6,7,NaN
43449,48,395,'LITTLE BRAZOS RIVER',30552406.0,96393020.0,2.0,9.0,1920.0,3,10.0,7,5,7,7,N,NaN
13170,48,371,'DRAW',30492902.0,102002954.0,1.0,1.0,1978.0,1,19.0,N,N,N,8,7,NaN

In [28]:
## call the bottom 6

dfbi.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [29]:
## call the year built column using dot notation

##notes from Sandeep: calling a series
## df.name_of_series
## Note: this is called dot notation.
## It is not the preferred method but it is common.

dfbi.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [31]:
# Cool

In [32]:
## call FEATURES_DESC_006A as a series using square bracket notation
dfbi["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [33]:
## what are the unique owner codes?
dfbi["OWNER_022"].unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

In [34]:
dfbi["OWNER_022"].nunique()

32

### What do these codes mean?

In [35]:
# The owner code is associated with this list of owners: https://www.fhwa.dot.gov/bridge/mtguide.pdf. 
# For example 68 is the bureau of land management